# Generated by Django 4.1.13 on 2024-02-09 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_message_conversation_alter_message_user_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="users",
            field=models.ManyToManyField(
                related_name="conversations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
